default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: 127.0.0.1

development:
  <<: *default
  database: book_output_development

test:
  <<: *default
  database: book_output_test

production:
  <<: *default
  database: book_output_production
  username: book_output
  password: <%= ENV['BOOK_OUTPUT_DATABASE_PASSWORD'] %>
